# Header
menu:
  Home: /
  Projects: /projects
  About: /about
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- archive
- links

links:
  Xiao3d: http://xiao3d.me
  NodeWee: http://nodewee.me
  "匆匆那年：ptbsare's blog": http://ptbsare.org
  "The Bloom of Youth | 锦瑟华年": http://kuangqi.me
  "Hakale's note": http://hakale.cn


# Miscellaneous

switch_banner: true

google_analytics: UA-40682162-1
