# Header
menu:
  Home: /
  Projects: /projects
  About: /about
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- archive

# Miscellaneous
favicon: /favicon.ico

switch_banner: true

google_analytics: UA-40682162-1