# Header
menu:
  Home: /
  Projects: /projects
  About: /about
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- myapps
- recent_posts
- archive
- links

links:
  NodeWee: http://nodewee.github.io
  "匆匆那年：ptbsare's blog": http://ptbsare.org
  "The Bloom of Youth | 锦瑟华年": http://kuangqi.me
  "Hakale's note": http://hakale.cn
  Hacer: http://hacer.cc
  创造狮导航: http://chuangzaoshi.com
  "Chay's Blog": https://www.chunyuip.com


# Miscellaneous

switch_banner: true

google_analytics: UA-40682162-1

disqus_shortname: blanboom
